### PR TITLE
Make subpixel positioning match that of Gecko.

### LINKED ISSUE #1270: Positioning of glyphs on macOS is wrong
I showed this to @kvark in real life.

### PR DESCRIPTION
**Pull request by glennw**
Simplify the quantization function, and add unit tests.

Modify the shader to correctly add the glyph subpixel offset
before truncating the value.

With these changes, the glyph rendering is pixel-perfect with
Gecko in all the test cases I checked.

Fixes #1270.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1715)

### CODE REVIEW

**Comment by glennw** [comment]
Gecko try:

https://hg.mozilla.org/try/rev/1b48b00b737c51379cb7db3d3c9d74705132f11c
https://treeherder.mozilla.org/#/jobs?repo=try&revision=1b48b00b737c51379cb7db3d3c9d74705132f11c

Tested ok on Servo / wrench.

File: webrender_api/src/font.rs [hunk 1]
```diff
@@ -274,3 +267,53 @@ pub struct GlyphInstance {
...
+    use super::{FontRenderMode, SubpixelOffset};
+
+    #[test]
+    fn test_subpx_quantize() {
+        let rm = FontRenderMode::Subpixel;
+
+        assert_eq!(rm.subpixel_quantize_offset(0.0), SubpixelOffset::Zero);
+        assert_eq!(rm.subpixel_quantize_offset(-0.0), SubpixelOffset::Zero);
+
+        assert_eq!(rm.subpixel_quantize_offset(0.1), SubpixelOffset::Zero);
```
Comment (kvark) [inline webrender_api/src/font.rs]: nit: could be nicer if those `subpixel_quantize_offset` calls are batched per expected `SubpixelOffset`

**Comment by kvark** [comment]
Tests are green, merging.
@bors-servo r+
