### PR TITLE
Ensure calling VertexDataTexture::update always guarantees texture() to succeed.

### LINKED ISSUE #3184: Reftests are panicking after #3183.
After #3183 running:

```
$ ../target/debug/wrench show reftests/text/blank.yaml
```

Panics with:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
```

Because in `bind_frame_data`, `frame.prim_headers.headers_float` is empty, and thus we don't initialize the texture at all. And we panic when calling `texture()` on the line below.

cc @bholley

### PR DESCRIPTION
**Pull request by emilio**
Alternative is stop assuming there's a texture, which we may or may not want to
do (happy to do that, but I know Bobby has in-flight patches for a bunch of the
texture stuff, so this probably is less breaking).

Fixes #3184

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3185)

### CODE REVIEW

File: webrender/src/device/gl.rs [hunk 1]
```diff
@@ -1232,7 +1232,7 @@ impl Device {
                     0,
                     desc.external,
                     desc.pixel_type,
-                    pixels.map(texels_to_u8_slice),
+                    pixels.and_then(texels_to_u8_slice),
```
Comment (kvark) [inline webrender/src/device/gl.rs]: I don't think this is correct. If the slice is provided, we exactly X bytes of data. Just ignoring empty data slices and treating them as storage allocation without initialization is something we shouldn't need to do.

**Comment by kvark** [comment]
@bors-servo r-
let's not create 0x0 textures :)

**Comment by kvark** [comment]
Thanks!
@bors-servo r+
