### PR TITLE
pipe through a scene_id to distinguish cached pictures

### LINKED ISSUE #2769: async scene building: cache collisions from reused picture ids
On my linux machine with async-scene-building, if I open this in one tab:

```
data:text/html,<div style="width: 400px;text-shadow: 1px 1px 2px green;">Hello there my name is alexis and this is my amazing test-case for shadows being broken under async scene building
```

and then open this in a second tab (identical except the shadow is red):

```
data:text/html,<div style="width: 400px;text-shadow: 1px 1px 2px red;">Hello there my name is alexis and this is my amazing test-case for shadows being broken under async scene building
```

the second tab has a green shadow, as it is using the cached shadow picture (really the final blur picture) from the other tab.

The issue is that async scene building repeatedly creates new `FrameBuilder::empty()`'s, resetting the picture id to 0 *and* that the picture cache doesn't factor in scene/document id's.

### PR DESCRIPTION
**Pull request by Gankro**
fixes #2769

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2776)

### CODE REVIEW

**Comment by Gankro** [comment]
CI failure looks like an intermittent?

**Comment by gw3583** [comment]
Yep, probably related to #2775.

File: webrender/src/render_backend.rs [hunk 1]
```diff
@@ -213,6 +213,7 @@ impl Document {
             &self.output_pipelines,
             &self.frame_builder_config,
             &mut self.current.scene,
+            0,
```
Comment (kvark) [inline webrender/src/render_backend.rs]: why are we passing 0 here?

File: webrender/src/render_backend.rs [hunk 2]
```diff
@@ -424,6 +427,7 @@ pub struct RenderBackend {
     recorder: Option<Box<ApiRecordingReceiver>>,
     sampler: Option<Box<AsyncPropertySampler + Send>>,
 
+    last_scene_id: u64,
```
Comment (kvark) [inline webrender/src/render_backend.rs]: nit: any specific reason for not using `usize`?

Comment (Gankro) [reply webrender/src/render_backend.rs]: because all our other ids are 64-bit unconditionally (less platform-specificness)

File: webrender/src/render_backend.rs (hunk 1 above)
Comment (Gankro) [reply webrender/src/render_backend.rs]: because the value isn't necessary on the sync path, and also we plan to remove this path altogether soon, right?

Comment (kvark) [reply webrender/src/render_backend.rs]: please put a comment then saying that this is not used because the picture IDs get reset. Frankly, it seems easier to just put the correct value in here in the first place

Comment (Gankro) [reply webrender/src/render_backend.rs]: there is a comment elsewhere, where the purpose of this value is explained, but you're right, i'll look at piping it through properly. i did this when i was just figuring out how everything piped together

**Comment by kvark** [comment]
Thanks, all good from my side to ship.

**Comment by kvark** [comment]
@Gankro please rebase and r=me

**Comment by gw3583** [comment]
@Gankro I think this needs a rebase in order to pick up some unrelated rawtest fixes, then r=kvark.

**Comment by Gankro** [comment]
(sorry been sick this week, will get to this when i'm feeling better)
