### PR TITLE
remove broken optimization, fixes #1682

### LINKED ISSUE #1682: Crash on macos when opening new tab: missing scroll_node_id
Crashing on `let scroll_node = &self.clip_scroll_tree.nodes[&group.scroll_node_id];` in `recalculate_clip_scroll_groups`.

```
hread 'RenderBackend' panicked at 'no entry found for key', src/libcore/option.rs:823
stack backtrace:
   0:        0x114c40ca3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h884a721e113c3303
   1:        0x114c4d163 - std::panicking::default_hook::{{closure}}::h7a7d734b2824d103
   2:        0x114c4cdac - std::panicking::default_hook::h3eb11bd6cbfdc331
   3:        0x114c4f2d7 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
   4:        0x114c4f174 - std::panicking::begin_panic::h69fe06a9d67b6165
   5:        0x114c4f0e2 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
   6:        0x114c4f047 - rust_begin_unwind
   7:        0x114c62230 - core::panicking::panic_fmt::hfedd6515bcee8bb1
   8:        0x114c6229d - core::option::expect_failed::h28a2a19f2decdd9c
   9:        0x114a6f26d - <core::option::Option<T>>::expect::hac168a503560cf99
  10:        0x114a6aa40 - <std::collections::hash::map::HashMap<K, V, S> as core::ops::Index<&'a Q>>::index::h49667e24ac931475
  11:        0x114aac70b - webrender::frame_builder::LayerRectCalculationAndCullingPass::recalculate_clip_scroll_groups::ha12a9988683a7b11
  12:        0x114aac123 - webrender::frame_builder::LayerRectCalculationAndCullingPass::run::hd3e2520f54469c0c
  13:        0x114aac0d7 - webrender::frame_builder::LayerRectCalculationAndCullingPass::create_and_run::h60f36bf6dcf35778
  14:        0x114aabaf5 - webrender::frame_builder::FrameBuilder::build::hc5fbbbd64c8dd9a0
  15:        0x114aa5016 - webrender::frame::Frame::build_frame::{{closure}}::h56c88a7da31406a1
  16:        0x114a6e43d - <core::option::Option<T>>::map::h1fbda1ea03fdfd04
  17:        0x114aa4efd - webrender::frame::Frame::build_frame::h10c00026a03fa944
  18:        0x114aa4e0b - webrender::frame::Frame::build::hecb5934eb68e2522
  19:        0x114ab7da8 - webrender::render_backend::Document::render::h1d7175be681900e6
  20:        0x114ab89b3 - webrender::render_backend::RenderBackend::process_document::h8740921e449148ef
  21:        0x114ab8f50 - webrender::render_backend::RenderBackend::run::h9a2d1e5f24ff6a6d
  22:        0x114a3e3da - webrender::renderer::Renderer::new::{{closure}}::hb06ffa5ff03ac526
  23:        0x1149c69dd - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f66ed1d6c9dd93d
  24:        0x114adb5bd - std::thread::Builder::spawn::{{closure}}::{{closure}}::h8e479e38eb51410d
  25:        0x114b0cd0d - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::hb2290a092864c045
  26:        0x114adbc8d - std::panicking::try::do_call::h2c53bc107a155b7c
Redirecting call to abort() to mozalloc_abort
```

https://github.com/servo/webrender/commit/0d6194ef44b56344132583987f59716f471a96a4 looks very suspicious.

### PR DESCRIPTION
**Pull request by Gankro**
If we skip a stacking context with clips that are referenced externally, this corrupts the clip_scroll tree. Just as a general safety thing, I'm completely removing this (marginal?) optimization to avoid this sort of problem from cropping up again.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1683)

### CODE REVIEW

File: webrender/src/frame.rs [hunk 1]
```diff
@@ -437,11 +437,6 @@ impl Frame {
                 stacking_context.mix_blend_mode_for_compositing())
         };
 
-        if composition_operations.will_make_invisible() {
-            traversal.skip_current_stacking_context();
```
Comment (kvark) [inline webrender/src/frame.rs]: instead of removing the condition, maybe we should leave it in, comment out the inner 2 lines, and add a big loud TODO item?
